{% set name = "text_models" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/text_models-{{ version }}.tar.gz
  sha256: 80f242454450fbe14b8044f1609840b0a730d14e125523f3e3c17eb6169ade53

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - numpy
    - pip
    - python >=3.7
  run:
    - evomsa
    - python >=3.7

test:
  imports:
    - text_models
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ingeotec/text_models
  summary: Text Models
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgraffg
