{% set name = "text_models" %}
{% set version = "1.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/text_models-{{ version }}.tar.gz
  sha256: 9bb272e302af8747b4038c72a441742d0ed5e6eabad0ea719760f0a6ea93d2ea

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - numpy
    - pip
    - python {{ python_min }}
  run:
    - evomsa
    - python >={{ python_min }}

test:
  imports:
    - text_models
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ingeotec/text_models
  summary: Text Models
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgraffg
